services:
  app:
    container_name: todo
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    volumes:
      - './media:/code/media:rw'
      - '/var/log/todo/logs:/code/logs:rw'
      - '/srv/www/todo/static:/srv/www/todo/static:rwx'
      - '/srv/www/todo/media:/srv/www/todo/media:rwx'

    ports:
      - "8070:8070"

