# Generated by Django 5.1 on 2024-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(blank=True, max_length=252)),
                ('description', models.CharField(blank=True, max_length=504)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'todo',
                'ordering': ['-created_at'],
            },
        ),
    ]
